pipelines:
  - name: aiola_test
    steps:
      - name: step_1
        type: Bash
        configuration:
          environmentVariables:
            env1: gitBranch
        {{ include "pipeline.execution" .Values }}
