pipelines:
  - name: P_files_1
    steps:
      - name: S_files_1
        type: Bash
        configuration:
          environmentVariables:
            env1: gitBranch
            env2: sourceRepository
        execution:
          onExecute:
            - echo {{ get (.Files.Get "config-from-root.json" | fromJson) "message" }}
            - echo {{ get (.Files.Get "conf/config.json" | fromJson) "message" }}