valuesFilePath: values.yml

resources:
  - name: myFirstRepo
    type: GitRepo
    configuration:
      gitProvider: mygithub
      path: sourceRepository
      branches:
        include: {{ .Values.repoBranch }}

pipelines:
  - name: P_basic
    steps:
      - name: S_basic
        type: Bash
        configuration:
          environmentVariables:
            env1: gitBranch
            env2: sourceRepository
        execution:
          onExecute:
            - echo {{ .Values.gitBranch | quote }}