valuesFilePath: values.yml

pipelines:
  - name: P_tpl
    steps:
      - name: S_tpl
        type: Bash
        configuration:
          environmentVariables:
          {{ tpl (toYaml .Values.environmentVariables) . | indent 2 }}

        execution:
          onExecute:
            - echo {{ tpl (toYaml .Values.repoName) . | quote }}
