valuesFilePath: values.yml

pipelines:
  - name: P_data
    steps:
      - name: S_data
        type: Bash
        configuration:
          environmentVariables:
            env1: gitBranch
            env2: sourceRepository
        execution:
          onExecute:
            {{ $myDict := dict "name1" "value1" "name2" "value2" "name3" "value 3" }}
            - echo {{ get $myDict "name1" }}