valuesFilePath: values.yml

pipelines:
{{ if eq .Values.gitBranch "test" }}
  - name: P_flow
    steps:
      - name: S_flow
        type: Bash
        configuration:
          environmentVariables:
            env1: gitBranch
            env2: sourceRepository

        execution:
          onExecute:
            - echo test
{{ end }}