valuesFilePath: values.yml

pipelines:
  - name: P_tpl
    steps:
      - name: S_tpl
        type: Bash
        configuration:
          environmentVariables:
            env1: gitBranch

        execution:
          onExecute:
            - echo {{ tpl (toYaml .Values.repoName) . | quote }}
