valuesFilePath: values.yml

resources:
  - name: myFirstRepo
    type: GitRepo
    configuration:
      gitProvider: mygithub
      path: sourceRepository
      branches:
        include: {{ .Values.gitBranch }}

pipelines:
  - name: P2
    steps:
      - name: S2
        type: Bash
        configuration:
          environmentVariables:
            env1: gitBranch

        execution:
          onExecute:
            - {{ tpl .Values.templateAsVariable . }}