valuesFilePath: values.yml

pipelines:
  - name: P_tpl
    steps:
      - name: S_tpl
        type: Bash
        configuration:
          environmentVariables:
            {{- range $k, $v := .Values.environmentVariables }}
            {{ $k }}: {{ tpl (toYaml .Values.environmentVariables.$v) . }}
            {{- end }}

        execution:
          onExecute:
            - echo {{ tpl (toYaml .Values.repoName) . | quote }}
