valuesFilePath: values.yml
resources:
  - name: myFirstRepo
    type: GitRepo
    configuration:
      gitProvider: mygithub
      path: sourceRepository
      branches:
        include: {{ .Values.gitBranch }}

pipelines:
  - name: P1
    steps:
      - name: S1
        type: Bash
        configuration:
          environmentVariables:
            env1: gitBranch
            env2: sourceRepository
        execution:
          onExecute:
            - echo {{ .Files.Get "config.toml" }}
            - echo {{ .Files.Get "config.txt" }}
            - echo {{ get (.Files.Get "config.json" | fromJson) "message" }}