valuesFilePath: values.yml

pipelines:
  - name: P_files
    steps:
      - name: S_files
        type: Bash
        configuration:
          environmentVariables:
            env1: gitBranch
            env2: sourceRepository
        execution:
          onExecute:
            - echo {{ get (.Files.Get "config.json" | fromJson) "message" }}
            - echo {{ get (.Files.Get "conf/config.json" | fromJson) "message" }}
            - echo {{ get (.Files.Get "conf/conf/config.json" | fromJson) "message" }}