{{- define "pipe.additionalEnvs" -}}
  env3: additional
{{ end -}}

valuesFilePath: values.yml

pipelines:
  - name: P_{{ include "sanity-name" . }}
    steps:
      - name: S_define_x
        type: Bash
        configuration:
          environmentVariables:
            env1: gitBranch
            env2: sourceRepository
            {{ include "pipe.additionalEnvs" . }}
            sanityName: {{ include "sanity-name" . }}
            sanityName1: {{ include "sanity.name1" . }}
        execution:
          onExecute:
            - echo test
